server:
  port: 8001
spring:
  datasource:
    url: jdbc:mysql://db1:3308/jpa001?serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: UserProvider
    
  ProviderVersion: UserProvider01
   


